name: "Run code analysis"

on:
  workflow_dispatch:

jobs:
  code_analysis:
    runs-on: ubuntu-latest
    name: Run code analysis
    steps:
      - uses: actions/checkout@v2
      - name: Run code analysis
        run: |
          docker run --rm -v "$(pwd)":/usr/source_code \
                 orenakto/akto-utils:latest cli extract \
                    --AKTO_SYNC="true" \
                    --AKTO_DASHBOARD_URL="http://a8461c33bea9c479196f00b34509ebcf-9285dcb52d810f62.elb.ap-south-1.amazonaws.com:8080" \
                    --AKTO_API_KEY="MrhwsiZSbSjeOBYjOQkyBdDAeEm7LfzXvCoexjOn" \
                    --IS_DOCKER="true" \
                    --API_COLLECTION_NAME="juice_shop_demo" | sed 's/\x1B\[[0-9;]\{1,\}[A-Za-z]//g' >> $GITHUB_STEP_SUMMARY