name: "Akto Code Analysis demo"

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  akto_code_analysis:
    runs-on: ubuntu-latest
    name: Akto code analysis demo
    steps:
      # To use this repository's private action,,,,,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Akto code analysis
        uses: akto-api-security/code-analysis-action@v1
        with:
          AKTO_DASHBOARD_URL: "http://abf2b3f314fc3429ea867be6aaff6238-de0a517233fca3a1.elb.ap-south-1.amazonaws.com:8080"
          AKTO_API_KEY: "igWcqBTRK27Yd0UC9nlpIZ9RwKtW9n5TVjB92tKu"
          API_COLLECTION_NAME: juice_shop_demo
