name: "Run code analysis"

on:
  workflow_dispatch:

jobs:
  code_analysis:
    runs-on: ubuntu-latest
    name: Run code analysis
    steps:
      - uses: actions/checkout@v2
      - name: Run code analysis
        run: |
          docker run --rm -v "$(pwd)":/usr/source_code \
                 orenakto/akto-utils:latest cli extract \
                    --AKTO_SYNC="true" \
                    --AKTO_DASHBOARD_URL="http://a0e069e6fbc6d423da7cfafc05a602fa-185d242a0b83f61f.elb.ap-south-1.amazonaws.com:8080" \
                    --AKTO_API_KEY="MrhwsiZSbSjeOBYjOQkyBdDAeEm7LfzXvCoexjOn" \
                    --IS_DOCKER="true" \
                    --API_COLLECTION_NAME="juice_shop_demo" | sed 's/\x1B\[[0-9;]\{1,\}[A-Za-z]//g' >> $GITHUB_STEP_SUMMARY
